### ISSUE TITLE
Grab some infrastructure provider

### ISSUE THREAD

**Issue by lwm** [giving-a-fuck-about-climate-change/carbon-doomsday#10]
https://www.openshift.com/grants/index.html

@titojankowski, wanna apply?

**Comment by titojankowski** [comment]
Ok, Applied! I imagine it will take a few days to hear back, what do we need in the meantime? Whats an alternative in case we're not selected?

**Comment by lwm** [comment]
I'm not sure which other provides give such a good offer. If we don't get it we can always use Heroku or something which has a free tier.

**Comment by titojankowski** [comment]
Ok! No ETA from the OpenShift application (it was a simple Google Form).

For comparison, OpenShift's startup program (not what we applied for) says
"Due to high demand, please allow up to 2 weeks for us to review your application. Only startups that have been accepted into the program will be notified."

The idea of potentially never being notified bugs me haha.

**Comment by titojankowski** [comment]
I created a free Heroku account for heroku@carbondoomsday.com.

I'd suggest we share this free account. The challenge with running a Heroku team project instead of "personal" is we wouldnt get free dynos. 
"Free dynos, which are available for personal apps, are not available to Teams."

@lwm I emailed you the login info and added your email as a forwarder on the email address linked. Let me know if there's another service you would prefer to use.

**Comment by titojankowski** [comment]
Fwiw I'm happy to chip in for a team account if it makes things easier. In that case we would setup a team project and add individuals as collaborators. ~$7/month

**Comment by lwm** [comment]
Great, all good for now then, we can use Heroku or OpenShift if we get accepted! Closing :+1:

**Comment by elliottsencan** [comment]
Heroku is just fine for now :D
